### ISSUE TITLE
Setting default value

### ISSUE THREAD

**Issue by avinashjoshi** [adammbalogh/key-value-store-memory#1]
I was thinking a default array to the construct function would be helpful. Something like:

``` php
public function __construct($store = [])
{
    $this->store = $store;
}
```

**Comment by adammbalogh** [comment]
@avinashjoshi It's valid. Would you like to create the PR for that?

**Comment by avinashjoshi** [comment]
I will work on a PR.

**Comment by adammbalogh** [comment]
PR for this issue: #2
