### ISSUE TITLE
Is there a way to get store value?

### ISSUE THREAD

**Issue by avinashjoshi** [adammbalogh/key-value-store-memory#3]
Is there a way to get the store value of a key. Something like this:

```
a:3:{s:1:"v";s:32:"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";s:1:"s";i:4210;s:2:"ts";i:1447698641;}
```

to store in database after a successful token generation?

**Comment by avinashjoshi** [comment]
Something in the lines of:

``` php
public function getStoreValue($key)
{
    if (!array_key_exists($key, $this->store)) {
        throw new KeyNotFoundException();
    }

    return $this->store[$key];
}
```

Any suggestions? I can create a PR if you are okay with this :)

**Comment by adammbalogh** [comment]
Why do you want to store the raw value in db?

**Comment by avinashjoshi** [comment]
I'm building an application which need to connect to multiple box accounts. I Want to keep the connection persistent and not want users to keep authorizing the app. 

I will be securely storing the tokens by encrypting them.

Is there a better way to achieve this? Maybe I'm missing something.

**Comment by adammbalogh** [comment]
What you need is not a mysql adapter?

**Comment by avinashjoshi** [comment]
You mean a custom adapter?

**Comment by adammbalogh** [comment]
Yeah. Now we have adapters for memory, file, redis... Maybe you would need a mysql (or as you said a custom adapter that fits) adapter to solve your problem.

**Comment by avinashjoshi** [comment]
Perfect! Thanks for the help @adammbalogh

**Comment by adammbalogh** [comment]
Your welcome.

(pls close this issue if you don't have any other question, thanks)
